INFRA-939 Revert htsjdk version back to 2.23.0
This matches the version used in Compar. The new version causes the
following error in the Smoke Test:

java.lang.IncompatibleClassChangeError: Found interface htsjdk.variant.variantcontext.Allele, but class was expected
	at com.hartwig.hmftools.compar.mutation.SomaticVariantData.fromContext(SomaticVariantData.java:270)
	at com.hartwig.hmftools.compar.mutation.SomaticVariantComparer.loadVariants(SomaticVariantComparer.java:375)
	at com.hartwig.hmftools.compar.mutation.SomaticVariantComparer.processSample(SomaticVariantComparer.java:99)
	at com.hartwig.hmftools.compar.ComparTask.processSample(ComparTask.java:84)
	at com.hartwig.hmftools.compar.ComparTask.call(ComparTask.java:53)
	at com.hartwig.hmftools.compar.Compar.run(Compar.java:82)
	at com.hartwig.hmftools.compar.Compar.main(Compar.java:105)
	at com.hartwig.pipeline.smoke.ComparAssert$ComparWrapper.run(ComparAssert.java:90)
	at com.hartwig.pipeline.smoke.ComparAssert.isEqualToTruthset(ComparAssert.java:42)
	at com.hartwig.pipeline.smoke.SmokeTest.runFullPipelineAndCheckFinalStatus(SmokeTest.java:168)
	at com.hartwig.pipeline.smoke.SmokeTest.runFullPipelineAndCheckFinalStatus(SmokeTest.java:127)
	at com.hartwig.pipeline.smoke.SmokeTest.tumorReference(SmokeTest.java:104)